[package]
name = "wrapping-in-range"
description = "Wrapping Arithmetic in a custom range"
version = "0.1.0"
edition = "2024"

[dependencies]
num-traits = "0.2"

[dev-dependencies]
proptest = "1.7.0"
