name: Bug Report
description: Create a report to help us improve
labels: bug
body:
  - type: markdown
    attributes:
      value: Thank you for filing a bug report! 🐛

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Please provide a short summary of the bug
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Steps to replicate the bug
    validations:
      required: true

  - type: textarea
    id: expected-outcome
    attributes:
      label: Expected Outcome
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual-outcome
    attributes:
      label: Actual Outcome
      description: What actually happened
    validations:
      required: true

  - type: textarea
    id: extra-info
    attributes:
      label: Additional information
      description: Please provide any additional information that could be useful
